### PR TITLE
use rx-stateful for deriving query state

### PR DESCRIPTION
**Pull request by michaelbe812**
Hi @eneajaho 
like the idea behind this repo! 

With this PR I want to demonstrate the usage of (rxStateful)[https://github.com/mikelgo/angular-kit/blob/main/libs/rx-stateful/README.md] which is a wrapper around observables and deriving automatically e.g. loading state and catching errors. Also behavior on re-fetching can be configured and different triggers to execute a refetch. 

This project is still WIP and I'm not fully happy with some API-design, nevertheless it is still useful I think. 

Looking forward what you say about it. If u have questions let me know (Docs are not sooo good I think 😅)

it could also be used to handle the other http-requests but I just wanted to showcase it on one.

aah and btw in the rxState demo pagination does not work - if i find some time i will fix it :-)

### CODE REVIEW

**Comment by eneajaho** [comment]
Hi @mikelgo 

In fact, what I'd like to see in this PR is to showcase how we can work with these libs in separate ways, meaning, rxState is a separate impl from the component store, I'd like to see the same thing with rx-stateful, it being its own impl. 

What do you think?

**Comment by michaelbe812** [comment]
I think it will not work out for rx-stateful as it is in fact no lib for state management (maybe the name suggests that).

In fact it is just a utility library/ wrapper around mainly Async observables like http requests. It does play well together as supplement for any state management solution. 

It handles all the hassle developers usually have to deal with async observables:
- deriving loading state correctly 
- Error handling 
- Refetching with correct loading and error state
- easy customization if  you want to keep the last value if a new request is running (can be helpful to prevent CLS issues)
- (Soon) emitting loading state in a way that you can prevent flickering spinners
- Multicasting 
- And some more minor things 

I hope I could explain it well :-)

**Comment by eneajaho** [comment]
Yeah, that makes sense. 

Can you duplicate the rxState impl then and also use your lib? this way they both can exist

**Comment by michaelbe812** [comment]
That is a good idea, I will do this. I Will update this PR and let u know when it's ready

**Pull request closed without merging**
